name: Control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pytest, flake8, and autopep8
        run: |
          pip install pytest
          pip install flake8 autopep8

      - name: Run tests
        run: |
          pytest

      - name: Run flake8
        run: |
          flake8 .

      - name: Run autopep8
        run: |
          autopep8 --in-place --recursive .
